export { prisma } from "./client.js";
export type { Database } from "./client.js";

// Re-exporta tipos e enums gerados pelo Prisma para consumo tipado nos modulos.
export {
  type Project,
  type Task,
  type KnowledgeItem,
  type Agent,
  type User,
  type Session,
  type Mission,
  type MissionEvent,
  type WorkerHeartbeat,
  type ScheduleRule,
  type OrganizationalGoal,
  type MissionLearning,
  type MissionDependency,
  type ChangeProposal,
  type DomainSignal,
  type WorkspaceSourceBinding,
  type WorkspaceGithubSnapshot,
  type CoordinationSignalLatch,
  type ActionExecution,
  type WorkGovernanceDecision,
  type OfficeDemand,
  type OfficeApprovalRequest,
  type OfficeDecisionTrace,
  type OfficeAutomation,
  OfficeDemandStatus,
  OfficeRiskLevel,
  OfficeAutonomyLevel,
  OfficePriority,
  OfficeApprovalStatus,
  OfficeConfidenceLevel,
  OfficeAutomationStatus,
  MissionStatus,
  MissionKind,
  MissionOrigin,
  MissionReadiness,
  GoalStatus,
  ApprovalStatus,
  DomainSignalStatus,
  DomainSignalEvaluationDecision,
  ActionExecutionStatus,
  CoordinationLatchStatus,
  UserRole,
  Prisma,
} from "@prisma/client";
